import React, { useState } from 'react';

const DataImporter = ({ onImport, onClose }) => {
    const [jsonInput, setJsonInput] = useState('');
    const [error, setError] = useState(null);

    const handleImport = () => {
        try {
            const parsedData = JSON.parse(jsonInput);
            onImport(parsedData);
            onClose();
        } catch (e) {
            setError("Invalid JSON format. Please check your input.");
        }
    };

    return (
        <div style={{
            position: 'fixed', top: 0, left: 0, right: 0, bottom: 0,
            background: 'rgba(0,0,0,0.8)', display: 'flex', alignItems: 'center', justifyContent: 'center',
            zIndex: 1000
        }}>
            <div style={{
                background: 'white', padding: '20px', borderRadius: '8px', width: '600px', maxWidth: '90%'
            }}>
                <h2>Import AI Data</h2>
                <p>Paste the JSON generated by ChatGPT below:</p>
                <textarea
                    value={jsonInput}
                    onChange={(e) => setJsonInput(e.target.value)}
                    style={{ width: '100%', height: '300px', fontFamily: 'monospace', marginBottom: '10px' }}
                    placeholder='{ "summary": "...", "experience": [...] }'
                />
                {error && <p style={{ color: 'red', marginBottom: '10px' }}>{error}</p>}
                <div style={{ display: 'flex', gap: '10px', justifyContent: 'flex-end' }}>
                    <button onClick={onClose} style={{ padding: '8px 16px', background: '#ccc', border: 'none', cursor: 'pointer' }}>Cancel</button>
                    <button onClick={handleImport} style={{ padding: '8px 16px', background: 'black', color: 'white', border: 'none', cursor: 'pointer' }}>Import</button>
                </div>
            </div>
        </div>
    );
};

export default DataImporter;
